version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          working_directory: server
          keys: 
            - pip-deps-{{ checksum "server/Pipfile.lock" }}
            - pip-deps-
      - run:
          working_directory: server
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          working_directory: server
          key: pip-deps-{{ checksum "server/Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          working_directory: server
          command: |
            pipenv run lint
            pipenv run type
            pipenv run format
